<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <LibsDir Condition="'$(LibsDir)' == ''">..\libs</LibsDir>
    <Version Condition="'$(Version)' == ''">1.0.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
    <Product>ShowBPM</Product>
    <Company>ShowBPM</Company>
    <Copyright>Copyright © ShowBPM</Copyright>
    <Description>ShowBPM</Description>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(LibsDir)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(LibsDir)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(LibsDir)\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="RDTools">
      <HintPath>$(LibsDir)\RDTools.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(LibsDir)\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(LibsDir)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(LibsDir)\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(LibsDir)\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(LibsDir)\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(LibsDir)\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(LibsDir)\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityModManager">
      <HintPath>$(LibsDir)\UnityModManager.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
