name: Build

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Checkout game DLLs
      uses: actions/checkout@v6
      with:
        repository: 2228293026/adofai-libs
        token: ${{ secrets.LIBS_ACCESS_TOKEN }}
        path: ../libs

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v3

    - name: Restore NuGet packages
      run: nuget restore ShowBPM.sln

    - name: Build
      run: msbuild ShowBPM.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ShowBPM-${{ github.sha }}
        path: |
          ShowBPM/bin/Release/net4.8/ShowBPM.dll
          Info.json
